networks:
  aas_default:
    external: true

services:
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
    ports:
      - '3081:8081'
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    networks:
      - aas_default

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - '3082:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/aas-registry.yml:/workspace/config/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - aas_default

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - '3083:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/sm-registry.yml:/workspace/config/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - aas_default

  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    container_name: aas-discovery
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./basyx/aas-discovery.properties:/application/application.properties
    ports:
      - '3084:8081'
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - aas_default

  mongo:
    image: mongo:5.0.10
    container_name: mongo
    ports:
      - '3017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    restart: always
    healthcheck:
      test: mongo
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aas_default

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    ports:
      - '1885:1883'
    volumes:
      - ./mosquitto:/mosquitto
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - mosquitto_sub -p 1883 -t 'topic' -C 1 -E -i probe -W 3
      interval: 5s
      timeout: 10s
      start_period: 1s
      retries: 3
    networks:
      - aas_default

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - '3086:8086'
      - '3999:9999'
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxpassword
      - DOCKER_INFLUXDB_INIT_ORG=basyx
      - DOCKER_INFLUXDB_INIT_BUCKET=basyx
      - >-
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=S18VeAlq042B4naMX31oqIaSGmUmOLAC-DV3VIdkxDJuAhTXLTVFEchyTSmCcUAmB7Wu94KgExzV8gJaDjzR3Q==
    restart: always
    networks:
      - aas_default

  telegraf:
    image: telegraf:1.29.1
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      INFLUX_TOKEN: >-
        S18VeAlq042B4naMX31oqIaSGmUmOLAC-DV3VIdkxDJuAhTXLTVFEchyTSmCcUAmB7Wu94KgExzV8gJaDjzR3Q==
    hostname: basyx_host
    restart: always
    depends_on:
      - influxdb
    networks:
      - aas_default

  aas-web-ui:
    image: eclipsebasyx/aas-gui:v2-241006
    container_name: aas-ui
    ports:
      - '3000:3000'
    environment:
      AAS_REGISTRY_PATH: http://192.168.100.21:3082/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://192.168.100.21:3083/submodel-descriptors
      AAS_REPO_PATH: http://192.168.100.21:3081/shells
      SUBMODEL_REPO_PATH: http://192.168.100.21:3081/submodels
      CD_REPO_PATH: http://192.168.100.21:3081/concept-descriptions
      AAS_DISCOVERY_PATH: http://192.168.100.21:3084/lookup/shells
      INFLUXDB_TOKEN: >-
        S18VeAlq042B4naMX31oqIaSGmUmOLAC-DV3VIdkxDJuAhTXLTVFEchyTSmCcUAmB7Wu94KgExzV8gJaDjzR3Q==
      DASHBOARD_SERVICE_PATH: http://192.168.100.21:3085/api/elements
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy
    networks:
      - aas_default

  dashboard-api:
    image: aaronzi/basyx-dashboard-api:SNAPSHOT_02
    container_name: dashboard-api
    ports:
      - '3085:8085'
    volumes:
      - ./basyx/aas-dashboard.yml:/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - aas_default

